name: CI
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                suite: [ channel1, channel3, channel4 ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install
                run: npm install

            -   name: Generate test files
                run: node src/test/generateTests.js

            -   name: Run Tests
                run: npm run test --suite ${{ matrix.suite }}

            -   uses: actions/upload-artifact@v1
                if: failure()
                with:
                    name: logs
                    path: logs
