name: CI
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install
                run: npm install

    Generate-test:
        name: Generate test files
        needs: [ build ]
        runs-on: ubuntu-latest
        steps:
            -   name: Generate test files
                run: node src/test/generateTests.js

    Channel1-Test:
        name: Channel1 Test
        needs: [ Generate-test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Run Tests
                run: npm run test --suite channel1

    Channel2-Test:
        name: Channel2 Test
        needs: [ Generate-test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Run Tests
                run: npm run test --suite channel2

    Channel3-Test:
        name: Channel3 Test
        needs: [ Generate-test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Run Tests
                run: npm run test --suite channel3

    Channel4-Test:
        name: Channel4 Test
        needs: [ Generate-test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Run Tests
                run: npm run test --suite channel4
