name: CI
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                channel: [ 'channel1', 'channel2', 'channel3', 'channel4' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install
                run: npm install

            -   name: Generate test files
                run: node generateTests.js

            -   name: Run Channel Tests
                run: npm run test --suite ${{ matrix.channel }}

            -   uses: actions/upload-artifact@v1
                if: failure()
                with:
                    name: logs
                    path: logs
